name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  automate:
    runs-on: ubuntu-18.04
    env:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true
      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '16.14.2'
          cache: yarn

      - run: yarn

      - run: npx --yes daniellockyer/monobundle
        working-directory: ghost/core
      
      - run: npm pack
        working-directory: ghost/core

      - run: mkdir -p .dist/release/
        working-directory: ghost/core

      - run: tar -xvzf "./ghost-$(echo $GITHUB_REF_NAME | tr -d "v").tgz" -C .dist/ 
        working-directory: ghost/core

      - run: cd .dist/package && zip -r "../release/Ghost-$(echo $GITHUB_REF_NAME | tr -d "v").zip" ./*
        working-directory: ghost/core

      - name: Check out action
        uses: actions/checkout@v2
        with:
          repository: juandelgadillo/action-ghost-release
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/action-ghost-release
      - name: Run my action
        uses: ./.github/actions/action-ghost-release
